### ISSUE TITLE
Sweep wallet Bitcoin Cash

### ISSUE THREAD

**Issue by HostFat** [cpacia/BitcoinCash-Wallet#2]
This feature can be very useful for many users that still need to claim their BCC :)

Maybe it should support WIF, BIP38 and mini private key

**Comment by cpacia** [comment]
Probably like a half day work to add it. The only real issue though is you need to sync from genesis to recover all utxos. That would take a decent amount of time. Currently it only syncs from a relatively recent checkpoint.

**Comment by cpacia** [comment]
Done - bip38
