### ISSUE TITLE
gave this a test drive and...

### ISSUE THREAD

**Issue by fyookball** [cpacia/BitcoinCash-Wallet#5]
hey Chris, 
great work on this wallet, looks cool and still seems to be in the alpha phase.
 
On the positive side, it saw a received tx right away!  

**Unforuntately, when i sent money out, it seems to have lost the funds.**  Don't worry it was only 60 cents. 

I dont see a history of either tx.  

The funds are still there in the address but the wallet shows 0 balance, i dont think the tx ever was broadcast?? 

other issues:
I had insufficient funds because of the fee and
it blanked out the address and amount and I had to
re-enter them.

I was unable to mouse click paste, had to use CTRL V.

The scroll bar within a scroll bar windowing is confusing
when i am in settings

i dont see an option to create a new wallet or new seed.

nothing happens when i click "need bitcoin?"

**Comment by cpacia** [comment]
Were you running the code out of master or using the 0.2.0 release?

Also can you look in the db file and see what you have in the utxo, stxo, and tx table. It will likely show the failed transaction.

**Comment by fyookball** [comment]
release.  what program should i use to view the db file?

**Comment by cpacia** [comment]
Any sqlite viewer.

**Comment by fyookball** [comment]
wasnt sure what to look for, didnt see anything obvious.

When I opened up the wallet again , the balance was restored...like the tx was never sent.
but here's the really weird part -- I opened it up a third time today, and now it looks like it was sent.

I think it just needs more testing.

**Comment by cpacia** [comment]
hmm. It could have been a syncing issue. I know there was a bug if your download peer disconnected which I'm fixing.
