### ISSUE TITLE
Blockchain height is stuck at 505089

### ISSUE THREAD

**Issue by dymurray** [cpacia/BitcoinCash-Wallet#8]
Hey there,

When I run this I see that the ticker value in the GUI is updated, but the Block height (set [here](https://github.com/cpacia/BitcoinCash-Wallet/blob/master/wallet.go#L132)) is stuck at 505089. I believe that it is not syncing properly? Also, I sent a transaction to my wallet but the value is still 0.00 even though it is a confirmed transaction. I did some debugging and found that [this](https://github.com/cpacia/BitcoinCash-Wallet/blob/master/wallet.go#L311) value is sitting at the value of the transaction so it is never being set as a confirmed amount.

I noticed a bunch of recent changes to blockchain.go and I am running from source. Could you help me figure out whats wrong? I also noticed blockchain.go is not passing tests anymore.

Thanks!
Dylan

**Comment by cpacia** [comment]
Hi dymurray. Should be fixed. Looks like two blocks had the same timestamp and I wasn't handling that edge case properly.
